### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by maasencioh** [cheminfo/hds-api#4]
@targos @lpatiny I put this issue here because I'm not sure where should be implemented (here or HDS), but there's only an addAttachment option for entry, doesn't exist an update, delete or get, am I wrong or should I program it? thanks!

**Comment by targos** [comment]
I'm not sure what you are talking about. The attachments are supposed to be handled automatically by hds, meaning that if you remove the field that contains the attachment, it is deleted. Same for replacement.
It is done here: https://github.com/cheminfo/hds/blob/5f8cd561f8c27272481fe6d5e5c8bdccc9ccc84d/src/kind.js#L172-L255
